[package]
name = "uethers"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum = "0.12.0"
hex = "0.4.3"
primitive-types = { version = "0.11.1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
ureq = { version = "2.4.0", features = ["json"] }